window.VISUAL_MODELS = [
    'gemma3',
    'llava',
    'llava-llama3',
    'bakllava',
    'llama3-vision',
    'llava-phi3',
    'phi3-vision',
    'llama3.2-vision',
    'minicpm-v',
    'moondream',
    'granite3.2-vision',
    'mistral-small3.1',
    'mistral-small3.2',
    'llama4',
    'qwen2.5vl',
];